#!/bin/bash

path=$(head -n 1 ".path")

cd $path
echo ""
pwd
echo ""

git branch -a
git gc
git fetch --prune origin

branch=$(git branch --show-current)

if [ $branch == devel ]
then
	git reset --hard origin/devel 
else
	git branch -f devel origin/devel
fi

echo ""
git branch -a
