#!/bin/bash

path=$(head -n 1 ".path")

commit=$1

echo "---------------------------------------------------------------------------------------------------------------"
echo "$commit"
echo "---------------------------------------------------------------------------------------------------------------"

cd $path

echo ""
pwd
echo ""

git status
git stage *
git status
read
git commit -m "$commit" && git push
