#!/bin/bash

path=$(head -n 1 ".path")

cd $path
echo ""
pwd
echo ""

git branch -a
cd

read -p "Enter branch name..."
filename=".branch-name"
nano .branch-name
branch=$(head -n 1 $filename)

cd $path

git branch -D $branch && git push -d origin $branch
